const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';

const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

const POPULAR_MOVIES_FETCH_REQUEST = 'POPULAR_MOVIES_FETCH_REQUEST';
const POPULAR_MOVIES_FETCH_SUCCESS = 'POPULAR_MOVIES_FETCH_SUCCESS';
const POPULAR_MOVIES_FETCH_FAILURE = 'POPULAR_MOVIES_FETCH_FAILURE';

const MOVIE_GENRES_FETCH_REQUEST = 'MOVIE_GENRES_FETCH_REQUEST';
const MOVIE_GENRES_FETCH_SUCCESS = 'MOVIE_GENRES_FETCH_SUCCESS';
const MOVIE_GENRES_FETCH_FAILURE = 'MOVIE_GENRES_FETCH_FAILURE';

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  POPULAR_MOVIES_FETCH_REQUEST,
  POPULAR_MOVIES_FETCH_SUCCESS,
  POPULAR_MOVIES_FETCH_FAILURE,
  MOVIE_GENRES_FETCH_REQUEST,
  MOVIE_GENRES_FETCH_SUCCESS,
  MOVIE_GENRES_FETCH_FAILURE,
};
